import { useEffect, useState } from 'react';
import { Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import api from './api/axiosConfig';
import { useAuth } from './context/AuthContext';

function AuthForm({ mode }) {
  const { login, register } = useAuth();
  const navigate = useNavigate();
  const [form, setForm] = useState({ email: '', password: '', role: 'client' });
  const [error, setError] = useState('');
  const submit = async (event) => {
    event.preventDefault(); setError('');
    try { await (mode === 'login' ? login(form) : register(form)); navigate('/dashboard'); }
    catch (err) { setError(err.response?.data?.message || err.response?.data?.errors?.[0]?.msg || 'Request failed'); }
  };
  return <main className="auth-shell"><section className="auth-copy"><p className="eyebrow">THE INDEPENDENT WORK MARKET</p><h1>Hustle<span>Hub</span><sup>+</sup></h1><p>Find focused talent. Build momentum. Keep every booking moving.</p></section><form className="form-panel" onSubmit={submit}><p className="eyebrow">{mode === 'login' ? 'WELCOME BACK' : 'OPEN YOUR STUDIO'}</p><h2>{mode === 'login' ? 'Sign in' : 'Create account'}</h2><label>Email<input placeholder="you@example.com" type="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Password<input placeholder="SecurePass123!" type="password" required value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label>{mode === 'register' && <label>Role<select value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}><option value="client">Client</option><option value="freelancer">Freelancer</option></select></label>}{error && <p className="error">{error}</p>}<button className="primary" type="submit">{mode === 'login' ? 'Enter workspace' : 'Start hustling'}</button><p className="switch">{mode === 'login' ? <>New here? <Link to="/register">Create an account</Link></> : <>Already registered? <Link to="/login">Sign in</Link></>}</p></form></main>;
}

function Shell({ children }) {
  const { user, logout } = useAuth();
  return <div className="app-shell"><header><Link className="brand" to="/dashboard">Hustle<span>Hub</span><sup>+</sup></Link><nav><Link to="/dashboard">Dashboard</Link>{user?.role === 'client' && <Link to="/gigs">Browse gigs</Link>}<Link to="/bookings">Bookings</Link>{user?.role !== 'client' && <Link to="/gigs">My gigs</Link>}</nav><button className="text-button" onClick={logout}>Sign out</button></header>{children}</div>;
}

function Dashboard() { const { user } = useAuth(); return <Shell><main className="content"><p className="eyebrow">YOUR WORKSPACE</p><h1>Good to see you, {user.email.split('@')[0]}.</h1><p className="lede">You are signed in as a <strong>{user.role}</strong>. Pick up where your work left off.</p><div className="stat-row"><div><span>01</span><strong>Workspace</strong><p>Ready for your next move.</p></div><div><span>02</span><strong>Protected</strong><p>JWT-secured access is active.</p></div><div><span>03</span><strong>Marketplace</strong><p>Book or publish with confidence.</p></div></div></main></Shell>; }

function Gigs() { const { user } = useAuth(); const [gigs, setGigs] = useState([]); const [form, setForm] = useState({ title: '', description: '', price: '' }); const [notice, setNotice] = useState(''); const load = () => api.get('/gigs').then(r => setGigs(r.data)); useEffect(() => { load().catch(() => setNotice('Could not load gigs. Start the API and try again.')); }, []); const create = async e => { e.preventDefault(); setNotice(''); try { await api.post('/gigs', { ...form, price: Number(form.price) }); setForm({ title: '', description: '', price: '' }); setNotice('Gig published.'); load(); } catch (err) { setNotice(err.response?.data?.message || 'Could not publish gig.'); } }; const book = async id => { try { await api.post('/bookings', { gigId: id }); setNotice('Booking confirmed.'); } catch (err) { setNotice(err.response?.data?.message || 'Could not create booking.'); } }; return <Shell><main className="content"><div className="page-heading"><div><p className="eyebrow">MARKETPLACE</p><h1>{user.role === 'client' ? 'Find your next specialist.' : 'Available offers.'}</h1></div></div>{user.role === 'client' && <form className="inline-form" onSubmit={create}><input required placeholder="Gig title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /><input required placeholder="Description" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /><input required min="0" type="number" placeholder="Price" value={form.price} onChange={e => setForm({ ...form, price: e.target.value })} /><button className="primary" type="submit">Publish gig</button></form>}{notice && <p className="notice">{notice}</p>}<div className="gig-grid">{gigs.map(gig => <article className="gig" key={gig._id}><p className="eyebrow">{gig.freelancerId?.email || 'HustleHub specialist'}</p><h2>{gig.title}</h2><p>{gig.description}</p><footer><strong>${gig.price}</strong>{user.role === 'client' && <button onClick={() => book(gig._id)}>Book now</button>}</footer></article>)}</div></main></Shell>; }

function Bookings() { const [items, setItems] = useState([]); const [transactions, setTransactions] = useState([]); const { user } = useAuth(); useEffect(() => { api.get('/bookings').then(r => setItems(r.data)); if (user.role !== 'client') api.get('/bookings/transactions').then(r => setTransactions(r.data)); }, [user.role]); return <Shell><main className="content"><p className="eyebrow">ACTIVITY</p><h1>{user.role === 'client' ? 'Your bookings.' : 'Incoming work.'}</h1><div className="list">{items.map(item => <div className="list-row" key={item._id}><div><strong>{item.gigId?.title || 'Booking'}</strong><p>{item.status} · ${item.amount}</p></div><span>{new Date(item.createdAt).toLocaleDateString()}</span></div>)}{!items.length && <p className="muted">No bookings yet.</p>}</div>{user.role !== 'client' && <><h2 className="section-title">Earnings</h2><div className="list">{transactions.map(item => <div className="list-row" key={item._id}><div><strong>Transaction</strong><p>{item.type}</p></div><strong>${item.amount}</strong></div>)}</div></>}</main></Shell>; }

function Protected({ children }) { const { user } = useAuth(); return user ? children : <Navigate to="/login" replace />; }
export default function App() { return <Routes><Route path="/login" element={<AuthForm mode="login" />} /><Route path="/register" element={<AuthForm mode="register" />} /><Route path="/dashboard" element={<Protected><Dashboard /></Protected>} /><Route path="/gigs" element={<Protected><Gigs /></Protected>} /><Route path="/bookings" element={<Protected><Bookings /></Protected>} /><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes>; }
